# modified to create multiple ingresses using range (interate over dict)
#   the special variable "." is remapped to $top, ...
#   range will map the values of the current ingress definition to "."
#   Furthermore "." has to be changed to "$" when using include "something"
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.app.environment }}
    owner: {{ .Values.app.owner }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 12 }}
spec:
  tls:
  {{- toYaml .Values.ingress.tls | nindent 12 }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.paths }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}
            port:
              number: {{ .Values.ingress.port }}
  ingressClassName: nginx  