apiVersion: v1
kind: ConfigMap
metadata:
  name: directus-env-configmap
  labels:
    {{- include "directus.labels" . | nindent 4 }}
data:
  DIRECTUS_INSTALL_TITLE: {{ .Values.env.directusTitle | quote }}
  DIRECTUS_DATABASE_CLIENT: {{ .Values.env.directusDatabaseClient | quote }}
  DIRECTUS_DATABASE_PORT: {{ .Values.env.directusDatabasePort | quote }}