apiVersion: v1
kind: Secret
metadata:
  name: directus-env-secrets
type: Opaque
data:
    DIRECTUS_KEY: {{ .Values.env.directusKey | b64enc }}
    DIRECTUS_SECRET: {{ .Values.env.directusSecret | b64enc }}
    DIRECTUS_DATABASE_USER: {{ .Values.env.directusDatabaseUsername | b64enc }}
    DIRECTUS_DATABASE_NAME: {{ .Values.env.directusDatabaseName | b64enc }}
    DIRECTUS_DATABASE_PASSWORD: {{ .Values.env.directusDatabasePassword | b64enc }}
    ADMIN_EMAIL: {{ .Values.env.directusEmail | b64enc }}
    ADMIN_PASSWORD: {{ .Values.env.directusPassword | b64enc }}
    DIRECTUS_DATABASE_HOST: {{ .Values.env.directusDatabaseHost | b64enc }}
    DIRECTUS_REDIS_HOST: {{ .Values.env.directusRedisHost | b64enc }}